'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProdStarCommunicator.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Chat Main&lt;/title&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''  &lt;tr&gt; 
        '''    &lt;td width=&quot;5%&quot;&gt;&lt;img src=&quot;ChatTextIcon.jpg&quot; width=&quot;18&quot; height=&quot;20&quot;&gt;&lt;/td&gt;
        '''    &lt;td width=&quot;95%&quot;&gt;&lt;font size=&quot;2&quot; face=&quot;Arial&quot;&gt;&amp;nbsp;&amp;nbsp;What&apos;s Hot&lt;/font&gt;&lt;/td&gt;
        '''  &lt;/tr&gt;
        '''  &lt;tr&gt; 
        '''    &lt;td&gt;&lt;img src=&quot;ChatTextIcon.jpg&quot; width=&quot;18&quot; height=&quot;20&quot;&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ChatMain1() As String
            Get
                Return ResourceManager.GetString("ChatMain1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Main Chat 2&lt;/title&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        '''&lt;/head&gt;
        '''
        '''&lt;body&gt;
        '''&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''  &lt;tr&gt; 
        '''    &lt;td&gt;&lt;font size=&quot;2&quot; face=&quot;Arial&quot;&gt;&lt;strong&gt;What&apos;s Hot for Friday, 10/01/99&lt;/strong&gt;&lt;/font&gt;&lt;/td&gt;
        '''  &lt;/tr&gt;
        '''  &lt;tr&gt; 
        '''    &lt;td&gt;&lt;font size=&quot;2&quot; face=&quot;Arial&quot;&gt;&amp;nbsp;&lt;/font&gt;&lt;/td&gt;
        '''  &lt;/tr&gt;
        '''  &lt;tr&gt; 
        '''    &lt;td&gt;&lt;font size=&quot;2&quot; face=&quot;Arial&quot;&gt;*On Prodig [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property ChatMain2() As String
            Get
                Return ResourceManager.GetString("ChatMain2", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
